# docker service rm lanl0rd_d0cker_js || true && docker stack deploy -c $HOME/d0cker/js/stack.yaml --resolve-image=never lanl0rd_d0cker

version: '3.7'

services:

  js:
    image: lanl0rd/js
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    command: tail -f /dev/null