# docker service rm lanl0rd_d0cker_certbot || true && docker stack deploy -c $HOME/d0cker/certbot/stack.yaml --resolve-image=never lanl0rd_d0cker

version: '3.7'

services:

  certbot:
    image: lanl0rd/certbot
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: tail -f /dev/null