# docker service rm lanl0rd_d0cker_py || true && docker stack deploy -c $HOME/d0cker/py/stack.yaml --resolve-image=never lanl0rd_d0cker

version: '3.7'

services:

  py:
    image: lanl0rd/py
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    command: tail -f /dev/null