# docker service rm lanl0rd_d0cker_java || true && docker stack deploy -c $HOME/d0cker/java/stack.yaml --resolve-image=never lanl0rd_d0cker

version: '3.7'

services:

  java:
    image: lanl0rd/java
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    command: tail -f /dev/null