# docker service rm d0cker_frpc || true && docker stack deploy -c $(pwd)/frpc.yaml --resolve-image=never d0cker

version: '3.7'

services:

  frpc:
    # image: lanl0rd/frp
    image: snowdreamtech/frpc
    networks:
      - host
    environment:
      - FRP_SERVER_ADDR=${FRP_SERVER_ADDR}
      - FRP_HTTP_PROXY_USER=${FRP_HTTP_PROXY_USER}
      - FRP_HTTP_PROXY_PASSWD=${FRP_HTTP_PROXY_PASSWD}
      - FRP_TOKEN=${FRP_TOKEN}
    volumes:
      - ./frpc.ini:/etc/frp/frpc-docker.ini
    command: /etc/frp/frpc -c /etc/frp/frpc-docker.ini

networks:
  host:
    external: true