# docker service rm d0cker_frpc || true && docker stack deploy -c $(pwd)/frpc.yaml --resolve-image=never d0cker

version: '3.7'

services:

  frpc:
    image: lanl0rd/frp
    networks:
        - host
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
    command: /etc/frp/frpc

networks:
  host:
    external: true