# docker service rm d0cker_frps || true && docker stack deploy -c $(pwd)/frps.yaml --resolve-image=never d0cker

version: '3.7'

services:

  frps:
    image: lanl0rd/frp
    networks:
        - host
    volumes:
      - ./frps.ini:/frp/frps.ini
    command: /etc/frp/frps

networks:
  host:
    external: true