# docker service rm lanl0rd_d0cker_php || true && docker stack deploy -c $HOME/d0cker/php/stack.yaml --resolve-image=never lanl0rd_d0cker

version: '3.7'

services:

  php:
    image: lanl0rd/php
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    command: tail -f /dev/null